agent:
  name: Cortex-R
  id: cortex_r_001
  description: >
    A reasoning-driven AI agent capable of using external tools
    and memory to solve complex tasks step-by-step

strategy:
  type: conservative   # Options: conservative, retry_once, explore_all
  max_steps: 3               # Maximum tool-use iterations before termination

memory:
  top_k: 3
  type_filter: tool_output # Options: tool_output, fact, query, all
  embedding_model: nomic-embed-text
  embedding_url: http://localhost:11434/api/embeddings

llm:
  text_generation: gemini
  embedding: nomic

persona:
  tone: concise
  verbosity: low
  behavior_tags: [rational, focusedm tool-using]

mcp_servers:
  - id: math
    script: math_server.py
    cwd: /Users/ravi/EAG-TheShadowCloneAI/S8/src/server/math_server
  - id: document
    script: rag_server.py
    cwd: /Users/ravi/EAG-TheShadowCloneAI/S8/src/server/rag_server
  - id: websearch
    script: websearch_server.py
    cwd: /Users/ravi/EAG-TheShadowCloneAI/S8/src/server/websearch_server

 
